apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

managedNodeGroups:
- name: expense1
  instanceType: m5.large
  desiredCapacity: 3
  spot: true ## 80% discount on price. But 2 mints only notice time. they will take over by AWS removed OnDemand
  